services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    command: npm run start
    volumes:
      - ./backend/src:/backend/src
      - ./backend/node_modules:/data/backend/node_modules
    env_file:
      - /backend/.env
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5050:3002"
    volumes:
      - ./frontend:/app/frontend


  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  mongodb: